# Generated by Django 4.0.4 on 2022-05-11 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('imdb_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='MOVIE id')),
                ('title_type', models.CharField(choices=[('short', 'короткометражка'), ('movie', 'фильм')], max_length=255, verbose_name='тип фильма')),
                ('name', models.CharField(max_length=255, verbose_name='название фильма')),
                ('is_adult', models.BooleanField(verbose_name='18+')),
                ('year', models.DateField(null=True, verbose_name='дата релиза')),
                ('genres', models.CharField(max_length=255, verbose_name='жанры')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('imdb_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='PERSON id')),
                ('name', models.CharField(max_length=255, verbose_name='имя актёра')),
                ('birth_year', models.DateField(null=True, verbose_name='дата рождения')),
                ('death_year', models.DateField(null=True, verbose_name='дата смерти')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.CreateModel(
            name='PersonMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='order')),
                ('category', models.CharField(max_length=255, verbose_name='category')),
                ('job', models.CharField(max_length=255, verbose_name='job')),
                ('characters', models.CharField(max_length=255, verbose_name='characters')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.person')),
            ],
        ),
    ]
