# Generated by Django 4.0.4 on 2022-05-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='movies',
            field=models.ManyToManyField(related_name='persons', through='cinema.PersonMovie', to='cinema.movie'),
        ),
    ]
