# Generated by Django 4.0.4 on 2022-05-26 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0004_activationtoken'),
        ('cinema', '0002_person_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='оценка')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='rating_value',
            field=models.FloatField(default=0.0, verbose_name='рейтинг'),
        ),
        migrations.AddField(
            model_name='movie',
            name='ratings',
            field=models.ManyToManyField(related_name='movies', through='cinema.MovieRating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personmovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.movie'),
        ),
        migrations.AlterField(
            model_name='personmovie',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.person'),
        ),
        migrations.AddField(
            model_name='movierating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.movie'),
        ),
        migrations.AddField(
            model_name='movierating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
